"""Add core pipeline tables

Revision ID: 9040670c79f9
Revises: 9d09dae7ccfa
Create Date: 2026-03-02 03:17:16.963006

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9040670c79f9"
down_revision: Union[str, Sequence[str], None] = "9d09dae7ccfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("github_url", sa.String(length=500), nullable=True),
        sa.Column("twitter_url", sa.String(length=500), nullable=True),
        sa.Column("current_company", sa.String(length=200), nullable=True),
        sa.Column("current_role", sa.String(length=200), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("linkedin_url"),
    )
    op.create_index(op.f("ix_persons_id"), "persons", ["id"], unique=False)
    op.create_table(
        "scoring_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("weights_json", sa.JSON(), nullable=False),
        sa.Column("thresholds_json", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_index(
        op.f("ix_scoring_config_id"), "scoring_config", ["id"], unique=False
    )
    op.create_table(
        "evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "IN_PROGRESS",
                "FAILED",
                "COMPLETED",
                "CANCELLED",
                "MANUAL_REVIEW",
                name="evaluationstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "stage",
            sa.Enum(
                "IDENTITY_RESOLUTION",
                "DATA_COLLECTION",
                "SIGNAL_EXTRACTION",
                "SCORING",
                "DECISION",
                name="evaluationstage",
            ),
            nullable=True,
        ),
        sa.Column("final_score", sa.Float(), nullable=True),
        sa.Column("decision", sa.String(length=50), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evaluations_id"), "evaluations", ["id"], unique=False)
    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("evaluation_id", sa.Integer(), nullable=False),
        sa.Column("execution_score", sa.Float(), nullable=True),
        sa.Column("technical_depth_score", sa.Float(), nullable=True),
        sa.Column("influence_score", sa.Float(), nullable=True),
        sa.Column("recognition_score", sa.Float(), nullable=True),
        sa.Column("raw_features_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evaluation_id"),
    )
    op.create_index(op.f("ix_signals_id"), "signals", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signals_id"), table_name="signals")
    op.drop_table("signals")
    op.drop_index(op.f("ix_evaluations_id"), table_name="evaluations")
    op.drop_table("evaluations")
    op.drop_index(op.f("ix_scoring_config_id"), table_name="scoring_config")
    op.drop_table("scoring_config")
    op.drop_index(op.f("ix_persons_id"), table_name="persons")
    op.drop_table("persons")
    # ### end Alembic commands ###
