"""Add sources column and cleanup models

Revision ID: 98df73aa40fc
Revises: 7cd5e1518503
Create Date: 2026-03-12 09:42:15.757343

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98df73aa40fc"
down_revision: Union[str, Sequence[str], None] = "7cd5e1518503"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop dependent tables first
    op.drop_index(
        op.f("ix_scraper_execution_logs_id"), table_name="scraper_execution_logs"
    )
    op.drop_index(
        op.f("ix_scraper_execution_logs_source"), table_name="scraper_execution_logs"
    )
    op.drop_table("scraper_execution_logs")

    op.drop_index(
        op.f("ix_profile_resolution_reports_id"),
        table_name="profile_resolution_reports",
    )
    op.drop_table("profile_resolution_reports")

    op.drop_index(op.f("ix_signals_id"), table_name="signals")
    op.drop_table("signals")

    op.drop_index(op.f("ix_scraper_scripts_id"), table_name="scraper_scripts")
    op.drop_index(op.f("ix_scraper_scripts_source"), table_name="scraper_scripts")
    op.drop_table("scraper_scripts")

    op.drop_index(op.f("ix_scoring_config_id"), table_name="scoring_config")
    op.drop_table("scoring_config")

    op.drop_index(
        op.f("ix_profile_intelligence_reports_id"),
        table_name="profile_intelligence_reports",
    )
    op.drop_table("profile_intelligence_reports")

    op.drop_index(op.f("ix_profile_evaluations_id"), table_name="profile_evaluations")
    op.drop_table("profile_evaluations")

    op.add_column("evaluations", sa.Column("sources", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evaluations", "sources")
    op.create_table(
        "scraper_execution_logs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("source", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column("url", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("script_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "script_name", sa.VARCHAR(length=120), autoincrement=False, nullable=True
        ),
        sa.Column("script_code", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("success", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["script_id"],
            ["scraper_scripts.id"],
            name=op.f("scraper_execution_logs_script_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("scraper_execution_logs_pkey")),
    )
    op.create_index(
        op.f("ix_scraper_execution_logs_source"),
        "scraper_execution_logs",
        ["source"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scraper_execution_logs_id"),
        "scraper_execution_logs",
        ["id"],
        unique=False,
    )
    op.create_table(
        "profile_evaluations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column(
            "github_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "website_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "twitter_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "signals",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "scrape_failures",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("score", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "deterministic_score", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "llm_score_adjustment", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "decision", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column("reasoning", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("profile_evaluations_pkey")),
    )
    op.create_index(
        op.f("ix_profile_evaluations_id"), "profile_evaluations", ["id"], unique=False
    )
    op.create_table(
        "profile_intelligence_reports",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "query_input", sa.VARCHAR(length=300), autoincrement=False, nullable=False
        ),
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.Column(
            "linkedin_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "qualifiers",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("status", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column("disambiguated", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "clarification_questions",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "candidates",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "sources",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("summary", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("profile_intelligence_reports_pkey")),
    )
    op.create_index(
        op.f("ix_profile_intelligence_reports_id"),
        "profile_intelligence_reports",
        ["id"],
        unique=False,
    )
    op.create_table(
        "scoring_config",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "version", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "weights_json",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "thresholds_json",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("scoring_config_pkey")),
        sa.UniqueConstraint("version", name=op.f("scoring_config_version_key")),
    )
    op.create_index(
        op.f("ix_scoring_config_id"), "scoring_config", ["id"], unique=False
    )
    op.create_table(
        "scraper_scripts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("source", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.Column("script_code", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("success_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("failure_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("last_error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "last_status", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("scraper_scripts_pkey")),
    )
    op.create_index(
        op.f("ix_scraper_scripts_source"), "scraper_scripts", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_scraper_scripts_id"), "scraper_scripts", ["id"], unique=False
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("evaluation_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "execution_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "technical_depth_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "influence_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "recognition_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "raw_features_json",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("signals_evaluation_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("signals_pkey")),
        sa.UniqueConstraint("evaluation_id", name=op.f("signals_evaluation_id_key")),
    )
    op.create_index(op.f("ix_signals_id"), "signals", ["id"], unique=False)
    op.create_table(
        "profile_resolution_reports",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "input_payload",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "resolved_name", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "resolved_company",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "resolved_designation",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "resolved_location",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "resolved_confidence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("ambiguity_flag", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "clarification_question", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "sources",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("aggregated_summary", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("profile_resolution_reports_pkey")),
    )
    op.create_index(
        op.f("ix_profile_resolution_reports_id"),
        "profile_resolution_reports",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###
