"""profile-resolution-report

Revision ID: 9d09dae7ccfa
Revises: c7ae57ceb56b
Create Date: 2026-03-01 15:39:41.523817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d09dae7ccfa'
down_revision: Union[str, Sequence[str], None] = 'c7ae57ceb56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
