"""Initial migration

Revision ID: c7ae57ceb56b
Revises: 
Create Date: 2026-02-23 02:11:23.792938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ae57ceb56b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_url', sa.String(length=500), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('scrape_failures', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('deterministic_score', sa.Integer(), nullable=False),
    sa.Column('llm_score_adjustment', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_evaluations_id'), 'profile_evaluations', ['id'], unique=False)
    op.create_table('scraper_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('script_code', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_scripts_id'), 'scraper_scripts', ['id'], unique=False)
    op.create_index(op.f('ix_scraper_scripts_source'), 'scraper_scripts', ['source'], unique=False)
    op.create_table('scraper_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.Column('script_name', sa.String(length=120), nullable=True),
    sa.Column('script_code', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scraper_scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_execution_logs_id'), 'scraper_execution_logs', ['id'], unique=False)
    op.create_index(op.f('ix_scraper_execution_logs_source'), 'scraper_execution_logs', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraper_execution_logs_source'), table_name='scraper_execution_logs')
    op.drop_index(op.f('ix_scraper_execution_logs_id'), table_name='scraper_execution_logs')
    op.drop_table('scraper_execution_logs')
    op.drop_index(op.f('ix_scraper_scripts_source'), table_name='scraper_scripts')
    op.drop_index(op.f('ix_scraper_scripts_id'), table_name='scraper_scripts')
    op.drop_table('scraper_scripts')
    op.drop_index(op.f('ix_profile_evaluations_id'), table_name='profile_evaluations')
    op.drop_table('profile_evaluations')
    # ### end Alembic commands ###
