"""add found_personas column

Revision ID: e40abd236a45
Revises: 98df73aa40fc
Create Date: 2026-03-15 01:31:26.551512

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e40abd236a45"
down_revision: Union[str, Sequence[str], None] = "98df73aa40fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("evaluations", sa.Column("found_personas", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evaluations", "found_personas")
    # ### end Alembic commands ###
